---
title: "p8131_hw9_mp3745"
author: "Matthew Parker"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(KMsurv)
library(survival)
library(survminer)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

Done by hand

## Problem 2

Done by hand

## Problem 3

Read in tongue data from KMsurv package
```{r}
data("tongue")
```

KM survival function
```{r}
# KM survival
km = survfit(Surv(time, delta) ~ type, data = tongue, conf.type = 'log')

# Plot survival function
ggsurvplot(km, conf.int = TRUE)
```

Estimated 1 year survival rate and 95% CI
```{r}
surv = summary(km, time = 52)

surv$surv[2]
```

For tumor type 1, the estimated 1 year survival rate is `r surv$surv[1]` with a 95% CI of (`r surv$lower[1]`, `r surv$upper[1]`). For tumor type 2, the estimated 1 year survival rate is `r surv$surv[2]` with a 95% CI of (`r surv$lower[2]`, `r surv$upper[2]`).

